In [1]:
import pandas as pd

In [7]:
info = {
    "Name" : ["Rahul", "prithi", "john"],
    "cgpa" : [9.9, 8.7, 9.5]
}

df = pd.DataFrame(info)

print(df)

     Name  cgpa
0   Rahul   9.9
1  prithi   8.7
2    john   9.5

In [8]:
df

     Name  cgpa
0   Rahul   9.9
1  prithi   8.7
2    john   9.5

In [9]:
s = pd.Series([1,2,3,4,5,6])

print(s)
print(type(s))

print(s[2])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>
3

In [11]:
s1 = pd.Series([23,34,22,21], index = ['A','B','C','D'])
print(s1)
print(s1['B'])
print(s1.index)

A    23
B    34
C    22
D    21
dtype: int64
34
Index(['A', 'B', 'C', 'D'], dtype='object')

In [13]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([10,20,30,40])

print(s1 + s2)

changed_s1 = s1.drop(2)
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
dtype: int64
0    1
1    2
2    3
3    4
dtype: int64
0    1
1    2
3    4
dtype: int64

In [ ]:
info = {
    "Name" : ["Rahul", "prithi", "john"],
    "cgpa" : [9.9, 8.7, 9.5]
}

df = pd.DataFrame(info)

print(df)

In [3]:
df = pd.read_csv("employee_data.csv")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [4]:
df1 = pd.read_json("data.json")

print(df1, type(df1))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [5]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [7]:
#Methods
df.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [9]:
df.tail(2)

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [11]:
df.sample() #random

   ID   Name  Age Department  Salary
3   4  David   45  Marketing   91000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [14]:
df.shape

(10, 5)

In [15]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000